version: '3,8'

services:
  api:
    container_name: api
    build: .
    command: npm run start:dev
    environment:
      - SERVICE_PORT=${SERVICE_PORT}
      - SERVICE_HOST=${SERVICE_HOST}
      - SERVICE_GLOBAL_PREFIX=${SERVICE_GLOBAL_PREFIX}
      - SERVICE_NAME=${SERVICE_NAME}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_HOST=postgres-test
      - TYPEORM_PORT=${TYPEORM_PORT}
    networks:
      - network-arr
    volumes:
      - ./src:/app/src
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - db
    restart: unless-stopped

  postgres-test:
    container_name: postgres-test
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    networks:
      - network-arr
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

networks:
  network-arr:
    driver: bridge